export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div>
      <h6 className="heading-l">deneme</h6>
      <h6 className="heading-m">deneme</h6>
      <h6 className="heading-s">deneme</h6>
    </div>
  );
}
